// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU0NGaU6O9IK-6VLhBt8OUsskhFyUh00w',
    appId: '1:154315740810:web:bbb5ed08f1eb81e66d7f73',
    messagingSenderId: '154315740810',
    projectId: 'chat-app-62d2b',
    authDomain: 'chat-app-62d2b.firebaseapp.com',
    storageBucket: 'chat-app-62d2b.appspot.com',
    measurementId: 'G-WV1RB6CGBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNibIcetU5BXb8jg0HzD36rew5fp70Ii4',
    appId: '1:154315740810:android:f5744d66402beb486d7f73',
    messagingSenderId: '154315740810',
    projectId: 'chat-app-62d2b',
    storageBucket: 'chat-app-62d2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEtlg2fRXtct6uD1QDxWzprbQidW5u01Y',
    appId: '1:154315740810:ios:d83d876acec1a9126d7f73',
    messagingSenderId: '154315740810',
    projectId: 'chat-app-62d2b',
    storageBucket: 'chat-app-62d2b.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEtlg2fRXtct6uD1QDxWzprbQidW5u01Y',
    appId: '1:154315740810:ios:bc17f33c710af4de6d7f73',
    messagingSenderId: '154315740810',
    projectId: 'chat-app-62d2b',
    storageBucket: 'chat-app-62d2b.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
